apiVersion: v1
kind: ReplicationController
metadata:
  name: web-api
spec:
  replicas: 3
  selector:
    app: web-api
  template:
    metadata:
      name: web-api
      labels:
        app: web-api
    spec:
      containers:
      - name: web-api
        image: rajatpandit/my-api:build-#build#
        ports:
        - containerPort: 8080
